version: "3.8"
services:
  caddy:
     image: caddy:latest
     restart: always
     ports:
       - 8001:8001
       - 8002:8002
#       - 80:80
#       - 443:443
     volumes:
       - ./__config/Caddyfile:/etc/caddy/Caddyfile
       - cdn:/var/www/cdn
     networks:
       - app-network
  api:
    build:
      context: .
      dockerfile: ./api/Dockerfile
    env_file: ./api/.env.docker
    environment:
      - BC_DB_URI=mongodb://admin:PASSWORD@mongo:27017/bookcars?authSource=admin&appName=bookcars
    restart: always
    depends_on:
      - mongo
    volumes:
      - cdn:/var/www/cdn/bookcars
    networks:
      - app-network
      - db-network

  mongo:
    image: mongo:latest
    restart: always
    environment:
      # Provide your credentials here
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: PASSWORD
    networks:
      - app-network
      - db-network

  backoffice:
    build: 
      context: .
      dockerfile: backoffice/Dockerfile
    depends_on:
      - api
    networks:
      - app-network

  frontend:
    build: 
      context: .
      dockerfile: ./frontend/Dockerfile
    depends_on:
      - api
    volumes:
      - cdn:/var/www/cdn/bookcars
    networks:
      - app-network

volumes:
  cdn:

networks:
  app-network:
  db-network:
